#!/bin/bash
# Dependency Update Skill
# Automatically checks for outdated dependencies and creates update PRs

set -euo pipefail

# ── Configuration ────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
BRANCH_PREFIX="deps/auto-update"
DATE_STAMP=$(date +%Y%m%d)
BRANCH_NAME="${BRANCH_PREFIX}-${DATE_STAMP}"

log()  { echo "[INFO]  $*"; }
warn() { echo "[WARN]  $*" >&2; }
err()  { echo "[ERROR] $*" >&2; exit 1; }

# ── Prerequisite checks ───────────────────────────────────────────────────────
check_prerequisites() {
  log "Checking prerequisites..."
  command -v python3 >/dev/null 2>&1 || err "python3 is required but not found"
  command -v pip    >/dev/null 2>&1 || err "pip is required but not found"
  command -v git    >/dev/null 2>&1 || err "git is required but not found"

  if [[ ! -f "$REPO_ROOT/pyproject.toml" ]]; then
    err "pyproject.toml not found at repo root: $REPO_ROOT"
  fi
  log "Prerequisites OK"
}

# ── Fetch outdated packages ───────────────────────────────────────────────────
get_outdated_packages() {
  log "Fetching outdated packages..."
  pip list --outdated --format=json 2>/dev/null || echo "[]"
}

# ── Update pyproject.toml constraints ────────────────────────────────────────
update_dependencies() {
  local outdated_json="$1"

  local count
  count=$(echo "$outdated_json" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))")

  if [[ "$count" -eq 0 ]]; then
    log "All dependencies are up to date."
    return 0
  fi

  log "Found $count outdated package(s). Attempting updates..."

  echo "$outdated_json" | python3 - <<'PYEOF'
import sys, json, subprocess, re, pathlib

data = json.load(sys.stdin)
pyproject = pathlib.Path("pyproject.toml").read_text()

updated = []
for pkg in data:
    name    = pkg["name"]
    latest  = pkg["latest_version"]
    # Bump any pinned or lower-bounded version for this package
    pattern = re.compile(
        rf'({re.escape(name)}\s*[><=!~]+\s*)[\d.]+',
        re.IGNORECASE
    )
    new_content, n = pattern.subn(rf'\g<1>{latest}', pyproject)
    if n:
        pyproject = new_content
        updated.append(f"{name} -> {latest}")
        print(f"  Updated {name} to {latest}")
    else:
        print(f"  Skipped {name} (no pinned constraint found)")

if updated:
    pathlib.Path("pyproject.toml").write_text(pyproject)
    print(f"\nWrote {len(updated)} update(s) to pyproject.toml")
PYEOF
}

# ── Install updated deps & run smoke tests ────────────────────────────────────
verify_updates() {
  log "Installing updated dependencies..."
  pip install -e "$REPO_ROOT[dev]" --quiet || warn "pip install encountered warnings"

  if command -v pytest >/dev/null 2>&1; then
    log "Running smoke tests..."
    pytest "$REPO_ROOT" -x -q --timeout=60 2>&1 | tail -20 || {
      warn "Tests failed after dependency update — reverting pyproject.toml"
      git -C "$REPO_ROOT" checkout -- pyproject.toml
      err "Dependency update rolled back due to test failures"
    }
  else
    warn "pytest not found; skipping smoke tests"
  fi
}

# ── Git: create branch & commit ───────────────────────────────────────────────
commit_changes() {
  cd "$REPO_ROOT"

  if git diff --quiet pyproject.toml; then
    log "No changes to commit."
    return 0
  fi

  log "Creating branch $BRANCH_NAME..."
  git checkout -b "$BRANCH_NAME" 2>/dev/null || git checkout "$BRANCH_NAME"
  git add pyproject.toml
  git commit -m "chore(deps): auto-update dependencies ${DATE_STAMP}"
  log "Committed dependency updates on branch $BRANCH_NAME"

  if command -v gh >/dev/null 2>&1; then
    log "Opening pull request via GitHub CLI..."
    gh pr create \
      --title "chore(deps): auto-update dependencies ${DATE_STAMP}" \
      --body "Automated dependency update generated by the dependency-update skill." \
      --base main \
      --head "$BRANCH_NAME" || warn "PR creation failed (branch may already have an open PR)"
  else
    warn "gh CLI not found; skipping PR creation"
  fi
}

# ── Main ──────────────────────────────────────────────────────────────────────
main() {
  log "=== Dependency Update Skill starting ==="
  cd "$REPO_ROOT"

  check_prerequisites

  local outdated
  outdated=$(get_outdated_packages)

  update_dependencies "$outdated"
  verify_updates
  commit_changes

  log "=== Dependency Update Skill complete ==="
}

main "$@"
